// Generated by gencpp from file pkg_robot/DoCarWashGoal.msg
// DO NOT EDIT!


#ifndef PKG_ROBOT_MESSAGE_DOCARWASHGOAL_H
#define PKG_ROBOT_MESSAGE_DOCARWASHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_robot
{
template <class ContainerAllocator>
struct DoCarWashGoal_
{
  typedef DoCarWashGoal_<ContainerAllocator> Type;

  DoCarWashGoal_()
    : number_of_cars(0)  {
    }
  DoCarWashGoal_(const ContainerAllocator& _alloc)
    : number_of_cars(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_of_cars_type;
  _number_of_cars_type number_of_cars;





  typedef boost::shared_ptr< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoCarWashGoal_

typedef ::pkg_robot::DoCarWashGoal_<std::allocator<void> > DoCarWashGoal;

typedef boost::shared_ptr< ::pkg_robot::DoCarWashGoal > DoCarWashGoalPtr;
typedef boost::shared_ptr< ::pkg_robot::DoCarWashGoal const> DoCarWashGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_robot::DoCarWashGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pkg_robot': ['/home/samu/robotics/catkin_ws/devel/share/pkg_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33bb64012f135ffd1019c71227972263";
  }

  static const char* value(const ::pkg_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33bb64012f135ffdULL;
  static const uint64_t static_value2 = 0x1019c71227972263ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_robot/DoCarWashGoal";
  }

  static const char* value(const ::pkg_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Definimos el objetivo (goal)\n"
"int32 number_of_cars \n"
;
  }

  static const char* value(const ::pkg_robot::DoCarWashGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number_of_cars);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoCarWashGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_robot::DoCarWashGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_robot::DoCarWashGoal_<ContainerAllocator>& v)
  {
    s << indent << "number_of_cars: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number_of_cars);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROBOT_MESSAGE_DOCARWASHGOAL_H
