// Generated by gencpp from file pkg_robot/DoCarWashFeedback.msg
// DO NOT EDIT!


#ifndef PKG_ROBOT_MESSAGE_DOCARWASHFEEDBACK_H
#define PKG_ROBOT_MESSAGE_DOCARWASHFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_robot
{
template <class ContainerAllocator>
struct DoCarWashFeedback_
{
  typedef DoCarWashFeedback_<ContainerAllocator> Type;

  DoCarWashFeedback_()
    : percent_cars_complete(0.0)  {
    }
  DoCarWashFeedback_(const ContainerAllocator& _alloc)
    : percent_cars_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_cars_complete_type;
  _percent_cars_complete_type percent_cars_complete;





  typedef boost::shared_ptr< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct DoCarWashFeedback_

typedef ::pkg_robot::DoCarWashFeedback_<std::allocator<void> > DoCarWashFeedback;

typedef boost::shared_ptr< ::pkg_robot::DoCarWashFeedback > DoCarWashFeedbackPtr;
typedef boost::shared_ptr< ::pkg_robot::DoCarWashFeedback const> DoCarWashFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pkg_robot': ['/home/samu/robotics/catkin_ws/devel/share/pkg_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf227faed0a440a437bef3d687cc66a3";
  }

  static const char* value(const ::pkg_robot::DoCarWashFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf227faed0a440a4ULL;
  static const uint64_t static_value2 = 0x37bef3d687cc66a3ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_robot/DoCarWashFeedback";
  }

  static const char* value(const ::pkg_robot::DoCarWashFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Definimos la retroalimentación (feedback)\n"
"float32 percent_cars_complete\n"
;
  }

  static const char* value(const ::pkg_robot::DoCarWashFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_cars_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DoCarWashFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_robot::DoCarWashFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_robot::DoCarWashFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_cars_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_cars_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROBOT_MESSAGE_DOCARWASHFEEDBACK_H
