// Generated by gencpp from file pkg_robot/sum_two_intRequest.msg
// DO NOT EDIT!


#ifndef PKG_ROBOT_MESSAGE_SUM_TWO_INTREQUEST_H
#define PKG_ROBOT_MESSAGE_SUM_TWO_INTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_robot
{
template <class ContainerAllocator>
struct sum_two_intRequest_
{
  typedef sum_two_intRequest_<ContainerAllocator> Type;

  sum_two_intRequest_()
    : a(0)
    , b(0)  {
    }
  sum_two_intRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sum_two_intRequest_

typedef ::pkg_robot::sum_two_intRequest_<std::allocator<void> > sum_two_intRequest;

typedef boost::shared_ptr< ::pkg_robot::sum_two_intRequest > sum_two_intRequestPtr;
typedef boost::shared_ptr< ::pkg_robot::sum_two_intRequest const> sum_two_intRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_robot::sum_two_intRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pkg_robot': ['/home/samu/robotics/catkin_ws/devel/share/pkg_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::pkg_robot::sum_two_intRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_robot/sum_two_intRequest";
  }

  static const char* value(const ::pkg_robot::sum_two_intRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::pkg_robot::sum_two_intRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sum_two_intRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_robot::sum_two_intRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_robot::sum_two_intRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROBOT_MESSAGE_SUM_TWO_INTREQUEST_H
