// Generated by gencpp from file pkg_robot/sum_two_int.msg
// DO NOT EDIT!


#ifndef PKG_ROBOT_MESSAGE_SUM_TWO_INT_H
#define PKG_ROBOT_MESSAGE_SUM_TWO_INT_H

#include <ros/service_traits.h>


#include <pkg_robot/sum_two_intRequest.h>
#include <pkg_robot/sum_two_intResponse.h>


namespace pkg_robot
{

struct sum_two_int
{

typedef sum_two_intRequest Request;
typedef sum_two_intResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum_two_int
} // namespace pkg_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pkg_robot::sum_two_int > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::pkg_robot::sum_two_int&) { return value(); }
};

template<>
struct DataType< ::pkg_robot::sum_two_int > {
  static const char* value()
  {
    return "pkg_robot/sum_two_int";
  }

  static const char* value(const ::pkg_robot::sum_two_int&) { return value(); }
};


// service_traits::MD5Sum< ::pkg_robot::sum_two_intRequest> should match 
// service_traits::MD5Sum< ::pkg_robot::sum_two_int > 
template<>
struct MD5Sum< ::pkg_robot::sum_two_intRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_robot::sum_two_int >::value();
  }
  static const char* value(const ::pkg_robot::sum_two_intRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_robot::sum_two_intRequest> should match 
// service_traits::DataType< ::pkg_robot::sum_two_int > 
template<>
struct DataType< ::pkg_robot::sum_two_intRequest>
{
  static const char* value()
  {
    return DataType< ::pkg_robot::sum_two_int >::value();
  }
  static const char* value(const ::pkg_robot::sum_two_intRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pkg_robot::sum_two_intResponse> should match 
// service_traits::MD5Sum< ::pkg_robot::sum_two_int > 
template<>
struct MD5Sum< ::pkg_robot::sum_two_intResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pkg_robot::sum_two_int >::value();
  }
  static const char* value(const ::pkg_robot::sum_two_intResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pkg_robot::sum_two_intResponse> should match 
// service_traits::DataType< ::pkg_robot::sum_two_int > 
template<>
struct DataType< ::pkg_robot::sum_two_intResponse>
{
  static const char* value()
  {
    return DataType< ::pkg_robot::sum_two_int >::value();
  }
  static const char* value(const ::pkg_robot::sum_two_intResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PKG_ROBOT_MESSAGE_SUM_TWO_INT_H
