// Generated by gencpp from file pkg_robot/sum_two_intResponse.msg
// DO NOT EDIT!


#ifndef PKG_ROBOT_MESSAGE_SUM_TWO_INTRESPONSE_H
#define PKG_ROBOT_MESSAGE_SUM_TWO_INTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pkg_robot
{
template <class ContainerAllocator>
struct sum_two_intResponse_
{
  typedef sum_two_intResponse_<ContainerAllocator> Type;

  sum_two_intResponse_()
    : sum(0)  {
    }
  sum_two_intResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sum_two_intResponse_

typedef ::pkg_robot::sum_two_intResponse_<std::allocator<void> > sum_two_intResponse;

typedef boost::shared_ptr< ::pkg_robot::sum_two_intResponse > sum_two_intResponsePtr;
typedef boost::shared_ptr< ::pkg_robot::sum_two_intResponse const> sum_two_intResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pkg_robot::sum_two_intResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pkg_robot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/melodic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'pkg_robot': ['/home/samu/robotics/catkin_ws/devel/share/pkg_robot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::pkg_robot::sum_two_intResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pkg_robot/sum_two_intResponse";
  }

  static const char* value(const ::pkg_robot::sum_two_intResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int64 sum\n"
;
  }

  static const char* value(const ::pkg_robot::sum_two_intResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sum_two_intResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pkg_robot::sum_two_intResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pkg_robot::sum_two_intResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PKG_ROBOT_MESSAGE_SUM_TWO_INTRESPONSE_H
