(cl:defpackage pkg_robot-msg
  (:use )
  (:export
   "<DOCARWASHACTION>"
   "DOCARWASHACTION"
   "<DOCARWASHACTIONFEEDBACK>"
   "DOCARWASHACTIONFEEDBACK"
   "<DOCARWASHACTIONGOAL>"
   "DOCARWASHACTIONGOAL"
   "<DOCARWASHACTIONRESULT>"
   "DOCARWASHACTIONRESULT"
   "<DOCARWASHFEEDBACK>"
   "DOCARWASHFEEDBACK"
   "<DOCARWASHGOAL>"
   "DOCARWASHGOAL"
   "<DOCARWASHRESULT>"
   "DOCARWASHRESULT"
  ))

