// Auto-generated. Do not edit!

// (in-package pkg_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoCarWashGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.number_of_cars = null;
    }
    else {
      if (initObj.hasOwnProperty('number_of_cars')) {
        this.number_of_cars = initObj.number_of_cars
      }
      else {
        this.number_of_cars = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoCarWashGoal
    // Serialize message field [number_of_cars]
    bufferOffset = _serializer.int32(obj.number_of_cars, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoCarWashGoal
    let len;
    let data = new DoCarWashGoal(null);
    // Deserialize message field [number_of_cars]
    data.number_of_cars = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_robot/DoCarWashGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '33bb64012f135ffd1019c71227972263';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Definimos el objetivo (goal)
    int32 number_of_cars 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoCarWashGoal(null);
    if (msg.number_of_cars !== undefined) {
      resolved.number_of_cars = msg.number_of_cars;
    }
    else {
      resolved.number_of_cars = 0
    }

    return resolved;
    }
};

module.exports = DoCarWashGoal;
