// Auto-generated. Do not edit!

// (in-package pkg_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoCarWashFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percent_cars_complete = null;
    }
    else {
      if (initObj.hasOwnProperty('percent_cars_complete')) {
        this.percent_cars_complete = initObj.percent_cars_complete
      }
      else {
        this.percent_cars_complete = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoCarWashFeedback
    // Serialize message field [percent_cars_complete]
    bufferOffset = _serializer.float32(obj.percent_cars_complete, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoCarWashFeedback
    let len;
    let data = new DoCarWashFeedback(null);
    // Deserialize message field [percent_cars_complete]
    data.percent_cars_complete = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_robot/DoCarWashFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bf227faed0a440a437bef3d687cc66a3';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Definimos la retroalimentación (feedback)
    float32 percent_cars_complete
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoCarWashFeedback(null);
    if (msg.percent_cars_complete !== undefined) {
      resolved.percent_cars_complete = msg.percent_cars_complete;
    }
    else {
      resolved.percent_cars_complete = 0.0
    }

    return resolved;
    }
};

module.exports = DoCarWashFeedback;
