// Auto-generated. Do not edit!

// (in-package pkg_robot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class DoCarWashResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.total_cars_cleaned = null;
    }
    else {
      if (initObj.hasOwnProperty('total_cars_cleaned')) {
        this.total_cars_cleaned = initObj.total_cars_cleaned
      }
      else {
        this.total_cars_cleaned = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type DoCarWashResult
    // Serialize message field [total_cars_cleaned]
    bufferOffset = _serializer.int32(obj.total_cars_cleaned, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type DoCarWashResult
    let len;
    let data = new DoCarWashResult(null);
    // Deserialize message field [total_cars_cleaned]
    data.total_cars_cleaned = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pkg_robot/DoCarWashResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2977e980bbc096b3b3c2043d941b53ab';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Definimos el resultado (result)
    int32 total_cars_cleaned
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new DoCarWashResult(null);
    if (msg.total_cars_cleaned !== undefined) {
      resolved.total_cars_cleaned = msg.total_cars_cleaned;
    }
    else {
      resolved.total_cars_cleaned = 0
    }

    return resolved;
    }
};

module.exports = DoCarWashResult;
